### ISSUE TITLE
UTF-8 with BOM

### ISSUE THREAD

**Issue by sntran** [beatrichartz/csv#20]
Hi,

I have a CSV saved as UTF-8 with BOM. The decoder stores the BOM together with the first header. Would this library try to strip out the BOM, or would it be the user's responsibility to decide whether to have the BOM in the CSV?

**Comment by beatrichartz** [comment]
The library currently expects a stream of utf-8 lines as input - typically you'd produce such a stream using [`File.stream!`](http://elixir-lang.org/docs/v1.0/elixir/File.html#stream!/3), which strips out the BOM in the resulting stream. Since the library is agnostic about where the stream is coming from though, it does not play any active part in stripping out / leaving in a BOM itself.

The same applies to encoding: If you want to encode with a BOM, you could also do that since the library does not directly write to a file.

**Comment by sanderhahn** [comment]
Seems that Elixir doesn't strip the BOM from the resulting stream even when passing utf8 encoding as a mode. Is this an omission in the Elixir implementation of streamed reading of utf8?

```
defmodule DecoderTest do
  test "ignores bom on parsing" do
    stream = "./fixtures/utf8-with-bom.csv" |> Path.expand(__DIR__) |> File.stream!([:utf8])

    lines = CSV.decode!(stream) |> Enum.into([])
    first_char = String.at(hd(hd(lines)), 0)
    refute first_char == "\ufeff"
  end
end
```

**Comment by sanderhahn** [comment]
Filtering the bom using `Stream.map` seems to be a workaround:

```
    File.stream!(path, [:utf8])
    |> Stream.map(&ignore_bom/1)
    |> CSV.decode(separator: ?;, headers: true)

  def ignore_bom(line) do
    if String.starts_with?(line, "\ufeff") do
      String.replace(line, "\ufeff", "")
    else
      line
    end
  end
```

**Comment by goofansu** [comment]
For anyone googled here: use `File.stream!([{:encoding, :utf8}, :trim_bom])` to use UTF-8 without BOM.
