### ISSUE TITLE
missing entry if parsing IO.stream

### ISSUE THREAD

**Issue by koyeung** [beatrichartz/csv#35]
it is found that different result obtained if `IO.stream` is used, instead of `File.stream!`, e.g.

```
iex(1)> "sample.csv" |> File.stream! |> CSV.Decoder.decode(headers: true)|>Enum.to_list
[%{"login" => "A", "name" => "Mr A", "shell" => "/bin/bash"},
 %{"login" => "admin", "name" => " Administrator", "shell" => " /bin/bash"},
 %{"login" => "root", "name" => " Root", "shell" => " /bin/sh"}]
iex(2)> f = File.open!("sample.csv")
#PID<0.176.0>
iex(3)> IO.stream(f, :line) |> CSV.Decoder.decode(headers: true) |> Enum.to_list 
[%{"login" => "admin", "name" => " Administrator", "shell" => " /bin/bash"}, 
 %{"login" => "root", "name" => " Root", "shell" => " /bin/sh"}]
```

content of "sample.csv":

```
login,name,shell
A,Mr A,/bin/bash
admin, Administrator, /bin/bash
root, Root, /bin/sh
```

May you let me know if you have any idea of the problem? thanks

module version: `1.4.0`

**Comment by beatrichartz** [comment]
Interesting, thanks for raising this! It seems like `headers: true` is somehow dropping two rows instead of one in this scenario. I'll be able to have a closer look tomorrow

**Comment by koyeung** [comment]
one more case: (if `Enum.to_list` is added before `CSV.Decoder.decode`, it works as expected.)

```
iex(1)> f = File.open!("sample.csv")
#PID<0.139.0>
iex(2)> IO.stream(f, :line) |> Enum.to_list |> CSV.Decoder.decode(headers: true) |> Enum.to_list 
[%{"login" => "A", "name" => "Mr A", "shell" => "/bin/bash"},
 %{"login" => "admin", "name" => " Administrator", "shell" => " /bin/bash"},
 %{"login" => "root", "name" => " Root", "shell" => " /bin/sh"}]
```

**Comment by beatrichartz** [comment]
Turns out that `IO.stream` is stateful whereas `File.stream!` is not:

```elixir
io_stream = "path/to/file.csv" |> File.open! |> IO.stream(:line)
io_stream |> Enum.take(1) # ["login,name,shell"]
io_stream |> Enum.take(1) # ["A,Mr A,/bin/bash"]
io_stream |> Enum.take(1) # ["admin, Administrator, /bin/bash"]
io_stream |> Enum.take(1) # ["root, Root, /bin/sh"]
io_stream |> Enum.take(1) # []
```

```elixir
file_stream = "path/to/file.csv" |> File.stream!
file_stream |> Enum.take(1) # ["login,name,shell"]
file_stream |> Enum.take(1) # ["login,name,shell"]
file_stream |> Enum.take(1) # ["login,name,shell"]
# ... etc
```

As of now, decoding with headers does not behave well when given a stateful stream. Fixing this will require some thought on how to extract headers from a stream and then making sure they do not get parsed as a row. Currently this is done via a `stream |> Stream.drop(1)`, and could be done with a `Stream.drop_while` instead, dropping the line if it matches already parsed headers. Obviously this would leave the edgecase when the first content line is exactly the same as the header line.

Thanks again for raising this. Out of interest, what's the case for using `IO.stream(f, :line)` in your code?

**Comment by koyeung** [comment]
Thanks for the investigation; it taught me a lot on handling stream.

The original code was like this: for filename `-`, read from `:stdio` (`IO.stream(:stdio, :line)`); for normal filename, read using `File.stream!`, i.e. handle reading from stdin and normal file uniformly.

thanks!

**Comment by koyeung** [comment]
as workaround, for stateful stream, pipe (and create another stream that repeat the header lines for each open):

```
iex(4)> defmodule Test do
...(4)> def buffer_stream_header(stream, n) do
...(4)>     Stream.concat(stream |> Enum.take(n), stream)
...(4)>   end
...(4)> end
iex(6)> f = File.open!("sample.csv")
#PID<0.301.0>
iex(7)> IO.stream(f, :line) |> Test.buffer_stream_header(1) |> CSV.Decoder.decode(headers: true) |> Enum.to_list 
[%{"login" => "A", "name" => "Mr A", "shell" => "/bin/bash"},
 %{"login" => "admin", "name" => " Administrator", "shell" => " /bin/bash"},
 %{"login" => "root", "name" => " Root", "shell" => " /bin/sh"}]
```

`Test.buffer_stream_header` effectively duplicate the first line and let the module `drop` it in the second run. (it works since in the first run, it read the first line only).

**Comment by beatrichartz** [comment]
I've put some thought into this, and I think this should be solved by the caller of this library, just as you have done in the solution outlined above. This could be enhanced further by not manipulating the original stream, but storing the decode result of the first line in a variable like so:

```elixir
stream = File.open!("sample.csv") |> IO.stream(f, :line)
headers = stream |> CSV.decode |> Enum.take(1)

# Now we simply pass the headers in like for a normal stream
stream |> CSV.decode(headers: headers) |> Enum.into([])
```

I'll close this since there are no good ways to detect this in the library itself, and I think the solutions outlined above should make for simple enough code.

**Comment by moxley** [comment]
@beatrichartz Why do you think it should be resolved by the caller? What if the caller doesn't know if the stream came from `IO.stream` or `File.stream!`? How would it know to apply the "fix" that @koyeung posted? Those two different stream generators behave differently when you consume the stream multiple times.

Just to be clear what I mean to consume the stream multiple times, this is an example:

```elixir
stream |> Enum.take(1)
stream |> Enum.take(1)
```

The above consumes the first element of the stream twice, thereby starting the underlying stream generator twice. That would be two calls to `start_fun` in [`Stream.resource`](http://elixir-lang.org/docs/stable/elixir/Stream.html#resource/3).

I don't see any documentation in [Stream](http://elixir-lang.org/docs/stable/elixir/Stream.html) that describes what should happen when you consume a stream multiple times, but don't think that is something that should a stream should be expected to support. What if the stream is backed by an expensive database query? You can't call `Enum.take(1)` on the stream, then consume the stream again without either executing the underlying database query again or add some complicated caching in the stream generator for that edge case.

You could design the library so that it only consumes the stream once instead of multiple times, and that would solve the problem.

Here's a simplified CSV parser that consumes the stream only once, solving the problem:

```elixir
defmodule DecodeCSV do
  def decode(stream, opts \\ []) do
    stream
    |> Stream.with_index
    |> Stream.transform(%{}, &(parse_line(&1, &2, opts)))
  end

  def parse_line({line, index}, csv_spec, opts) do
    if index == 0 && opts[:header] do
      header = split_row(line, opts)
      {[], csv_spec |> Map.put(:header, header)}
    else
      row = parse_row(line, csv_spec, opts)
      {[row], csv_spec}
    end
  end

  def parse_row(line, csv_spec, opts) do
    row = split_row(line, opts)
    if opts[:header] do
      convert_to_map(row, csv_spec)
    else
      row
    end
  end

  def split_row(line, _opts) do
    line
    |> String.rstrip
    |> String.split(",")
  end

  def convert_to_map(row, csv_spec) do
    zipped = Enum.zip(csv_spec.header, row)
    for {head, value} <- zipped, into: %{} do
      {head, value}
    end
  end
end

csv_string = "a,b\n1,2\n3,4"

{:ok, io} = csv_string |> StringIO.open
stream = io |> IO.binstream(:line)
IO.inspect(DecodeCSV.decode(stream) |> Enum.to_list)
# [["a", "b"], ["1", "2"], ["3", "4"]]

{:ok, io} = csv_string |> StringIO.open
stream = io |> IO.binstream(:line)
IO.inspect(DecodeCSV.decode(stream, header: true) |> Enum.to_list)
# [%{"a" => "1", "b" => "2"}, %{"a" => "3", "b" => "4"}]
```

**Comment by beatrichartz** [comment]
@moxley thanks for your comment! I do agree that if a solution handling any stream is possible it should be integrated into the library, and I appreciate the time you've taken to outline a possible solution - the library has been adjusted with a similar solution for `1.4.1`. Let me also clear up some confusion around what I'd consider the caller's concern:

There are two related but slightly different cases here: 
- In https://github.com/beatrichartz/csv/issues/39 you raised is an incompatibility with strings backed by a stateful resource - essentially a bug where lines get dropped without headers requested. This has been addressed in much the same way you laid out in your example.
- This issue, which is about providing headers for a stream backed by a stateful resource. While the new version works slightly better in that regard as well, there are still cases where this approach can fail: If streams are halted and restarted (by performing `Enum,take(1)` or similar and then evaluating the stream somewhere else), `headers: true` is going to give wrong headers for the second evaluation. Also, since this library assigns the parsing work to multiple workers in chunks, halting a stream is going to throw away some input if not handled carefully:

Problem 1:
```elixir
csv_string = "a,b\n1,2\n3,4\n5,6"
{:ok, io} = csv_string |> StringIO.open
stream = io |> IO.binstream(:line)

stream |> CSV.decode(headers: true, num_workers: 1, worker_work_ratio: 1) |> Enum.take(1)
# [%{"a" => "1", "b" => "2"}]

stream |> CSV.decode(headers: true, num_workers: 1, worker_work_ratio: 1) |> Enum.take(1)
# [%{"3" => "4", "5" => "6"}]

# see also your solution:
csv_string = "a,b\n1,2\n3,4\n5,6"
{:ok, io} = csv_string |> StringIO.open
stream = io |> IO.binstream(:line)

DecodeCSV.decode(stream, header: true) |> Enum.to_list
# [%{"a" => "1", "b" => "2"}]

DecodeCSV.decode(stream, header: true) |> Enum.to_list
# [%{"3" => "4", "5" => "6"}]
```

Problem 2 (Notice absence of worker config, which means the rest of the lines will be assigned for parsing and then thrown away on halt):
```elixir
csv_string = "a,b\n1,2\n3,4\n5,6"
{:ok, io} = csv_string |> StringIO.open
stream = io |> IO.binstream(:line)

stream |> CSV.decode(headers: true) |> Enum.take(1)
# [%{"a" => "1", "b" => "2"}]

stream |> CSV.decode(headers: true) |> Enum.take(1)
# []
```

There may be no documentation in the Stream module pointing to streams being rewound in general, but there are multiple tests in the stream module which would fail if this property would not hold, e.g https://github.com/elixir-lang/elixir/blob/v1.2.5/lib/elixir/test/elixir/stream_test.exs#L23 , https://github.com/elixir-lang/elixir/blob/v1.2.5/lib/elixir/test/elixir/stream_test.exs#L62 etc

Therefore I think it is still the caller's concern to extract headers if needed for subsequent calls if they're not avoidable alltogether via something like:

```elixir
headers = stream |> CSV.decode(headers: true, num_workers: 1, worker_work_ratio: 1) |> Enum.take(1)
```

Streams which are expected to be run like that / consumed in multiple runs should also always specify a `num_workers x worker_work_ratio` which is denominator of the n taken items (num_workers * worker_work_ratio = n)

```elixir
headers = stream |> CSV.decode(headers: true, num_workers: 5, worker_work_ratio: 5) |> Enum.take(25)
```

I'd also love to be able to address this in a sensible way, however I did not yet come upon a good solution. Let me know if you have some thoughts.

**Comment by moxley** [comment]
@beatrichartz Thank you for the explanation. That makes sense about the case where there are multiple workers decoding the CSV.
